// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqodvnlgmjwgbedzsmoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxb2R2bmxnbWp3Z2JlZHpzbW9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwODUyMTEsImV4cCI6MjA1NTY2MTIxMX0.wD9huih55qzpTxIUmE08l0BiJaMeDcelJX-fFCMXBXc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);